# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171105_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ext',
            new_name='text',
        ),
    ]
